name: Run RSS Script

on:
  schedule:
    # 定时任务设置为每天的 UTC 时间 02:00 运行
    - cron: '0 2 * * *'
  workflow_dispatch:  # 手动触发

jobs:
  run-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'  # 使用Python 3.11.9版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          SECOND_TELEGRAM_BOT_TOKEN: ${{ secrets.SECOND_TELEGRAM_BOT_TOKEN }}
          ALLOWED_CHAT_IDS: ${{ secrets.ALLOWED_CHAT_IDS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
          TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
        run: python rss.py
